# Em um arquivo como 'game_data/relics.py' ou diretamente em 'outlaw/data_manager.py'

relics = [
    # --- Relíquias Básicas (Menos Poderosas, Comuns) ---
    {
        "nome": "Caco de Telha",
        "tier": "Básica",
        "valor_moedas": 4,
        "energia_concedida": 0,
        "chance_obter_percentual": 80.0,
    },
    {
        "nome": "Folha Seca",
        "tier": "Básica",
        "valor_moedas": 5,
        "energia_concedida": 0,
        "chance_obter_percentual": 75.0,
    },
    {
        "nome": "Pedaço de Galho",
        "tier": "Básica",
        "valor_moedas": 6,
        "energia_concedida": 0,
        "chance_obter_percentual": 70.0,
    },
    {
        "nome": "Pedra Pequena",
        "tier": "Básica",
        "valor_moedas": 7,
        "energia_concedida": 0,
        "chance_obter_percentual": 65.0,
    },
    {
        "nome": "Concha Vazia",
        "tier": "Básica",
        "valor_moedas": 8,
        "energia_concedida": 0,
        "chance_obter_percentual": 60.0,
    },
    {
        "nome": "Tampinha de Garrafa",
        "tier": "Básica",
        "valor_moedas": 9,
        "energia_concedida": 0,
        "chance_obter_percentual": 55.0,
    },
    {
        "nome": "Fio de Linha",
        "tier": "Básica",
        "valor_moedas": 10,
        "energia_concedida": 0,
        "chance_obter_percentual": 50.0,
    },
    {
        "nome": "Pedaço de Pano",
        "tier": "Básica",
        "valor_moedas": 11,
        "energia_concedida": 0,
        "chance_obter_percentual": 45.0,
    },
    {
        "nome": "Botão Solto",
        "tier": "Básica",
        "valor_moedas": 12,
        "energia_concedida": 0,
        "chance_obter_percentual": 40.0,
    },
    {
        "nome": "Prego Enferrujado",
        "tier": "Básica",
        "valor_moedas": 13,
        "energia_concedida": 0,
        "chance_obter_percentual": 35.0,
    },
    {
        "nome": "Lixo Qualquer",
        "tier": "Básica",
        "valor_moedas": 15,
        "energia_concedida": 0,
        "chance_obter_percentual": 30.0,
    },
    {
        "nome": "Grama Arrancada",
        "tier": "Básica",
        "valor_moedas": 16,
        "energia_concedida": 0,
        "chance_obter_percentual": 25.0,
    },
    {
        "nome": "Pedaço de Vidro Quebrado",
        "tier": "Básica",
        "valor_moedas": 18,
        "energia_concedida": 0,
        "chance_obter_percentual": 20.0,
    },
    {
        "nome": "Poça de Lama Seca",
        "tier": "Básica",
        "valor_moedas": 19,
        "energia_concedida": 0,
        "chance_obter_percentual": 15.0,
    },
    {
        "nome": "Fio de Cabelo",
        "tier": "Básica",
        "valor_moedas": 20,
        "energia_concedida": 0,
        "chance_obter_percentual": 10.0,
    },
    {
        "nome": "Pedaço de Carvão",
        "tier": "Básica",
        "valor_moedas": 22,
        "energia_concedida": 0,
        "chance_obter_percentual": 9.0,
    },
    {
        "nome": "Pó de Poeira",
        "tier": "Básica",
        "valor_moedas": 23,
        "energia_concedida": 0,
        "chance_obter_percentual": 8.0,
    },
    {
        "nome": "Uma única Pena",
        "tier": "Básica",
        "valor_moedas": 25,
        "energia_concedida": 0,
        "chance_obter_percentual": 7.0,
    },
    {
        "nome": "Ramo Caído",
        "tier": "Básica",
        "valor_moedas": 27,
        "energia_concedida": 0,
        "chance_obter_percentual": 6.0,
    },
    {
        "nome": "Fragmento de Cerâmica",
        "tier": "Básica",
        "valor_moedas": 30,
        "energia_concedida": 0,
        "chance_obter_percentual": 5.0,
    },
    # --- Relíquias Comuns (Itens Básicos, Fáceis de Achar) ---
    {
        "nome": "Anel da Persuasão Leve",
        "tier": "Comum",
        "valor_moedas": 50,
        "energia_concedida": 1,
        "chance_obter_percentual": 4.5,
    },
    {
        "nome": "Capuz Comum",
        "tier": "Comum",
        "valor_moedas": 60,
        "energia_concedida": 1,
        "chance_obter_percentual": 4.0,
    },
    {
        "nome": "Cinto Simples",
        "tier": "Comum",
        "valor_moedas": 70,
        "energia_concedida": 2,
        "chance_obter_percentual": 3.5,
    },
    {
        "nome": "Frasco de Água",
        "tier": "Comum",
        "valor_moedas": 80,
        "energia_concedida": 2,
        "chance_obter_percentual": 3.0,
    },
    {
        "nome": "Luvas de Trabalho",
        "tier": "Comum",
        "valor_moedas": 90,
        "energia_concedida": 3,
        "chance_obter_percentual": 2.8,
    },
    {
        "nome": "Máscara de Poeira",
        "tier": "Comum",
        "valor_moedas": 100,
        "energia_concedida": 3,
        "chance_obter_percentual": 2.6,
    },
    {
        "nome": "Óculos de Leitura",
        "tier": "Comum",
        "valor_moedas": 110,
        "energia_concedida": 4,
        "chance_obter_percentual": 2.4,
    },
    {
        "nome": "Pingente Decorativo",
        "tier": "Comum",
        "valor_moedas": 120,
        "energia_concedida": 4,
        "chance_obter_percentual": 2.2,
    },
    {
        "nome": "Poção de Cura Menor",
        "tier": "Comum",
        "valor_moedas": 130,
        "energia_concedida": 5,
        "chance_obter_percentual": 2.0,
    },
    {
        "nome": "Saco de Pão",
        "tier": "Comum",
        "valor_moedas": 140,
        "energia_concedida": 5,
        "chance_obter_percentual": 1.8,
    },
    {
        "nome": "Cajado de Caminhada",
        "tier": "Comum",
        "valor_moedas": 150,
        "energia_concedida": 6,
        "chance_obter_percentual": 1.6,
    },
    {
        "nome": "Brincos Simples",
        "tier": "Comum",
        "valor_moedas": 160,
        "energia_concedida": 6,
        "chance_obter_percentual": 1.4,
    },
    {
        "nome": "Corda Fina",
        "tier": "Comum",
        "valor_moedas": 170,
        "energia_concedida": 7,
        "chance_obter_percentual": 1.2,
    },
    {
        "nome": "Estojo de Ferramentas Básicas",
        "tier": "Comum",
        "valor_moedas": 180,
        "energia_concedida": 7,
        "chance_obter_percentual": 1.1,
    },
    {
        "nome": "Fósforo Eterno",
        "tier": "Comum",
        "valor_moedas": 190,
        "energia_concedida": 8,
        "chance_obter_percentual": 1.0,
    },
    {
        "nome": "Gema Polida",
        "tier": "Comum",
        "valor_moedas": 200,
        "energia_concedida": 8,
        "chance_obter_percentual": 0.95,
    },
    {
        "nome": "Lanterna de Mão",
        "tier": "Comum",
        "valor_moedas": 210,
        "energia_concedida": 9,
        "chance_obter_percentual": 0.9,
    },
    {
        "nome": "Papiro em Branco",
        "tier": "Comum",
        "valor_moedas": 220,
        "energia_concedida": 9,
        "chance_obter_percentual": 0.85,
    },
    {
        "nome": "Vela de Cera",
        "tier": "Comum",
        "valor_moedas": 230,
        "energia_concedida": 10,
        "chance_obter_percentual": 0.8,
    },
    {
        "nome": "Amuleto da Proteção Simples",
        "tier": "Comum",
        "valor_moedas": 240,
        "energia_concedida": 10,
        "chance_obter_percentual": 0.75,
    },
    {
        "nome": "Cantil Simples",
        "tier": "Comum",
        "valor_moedas": 250,
        "energia_concedida": 11,
        "chance_obter_percentual": 0.7,
    },
    {
        "nome": "Escudo de Madeira",
        "tier": "Comum",
        "valor_moedas": 260,
        "energia_concedida": 11,
        "chance_obter_percentual": 0.65,
    },
    {
        "nome": "Frasco Vazio",
        "tier": "Comum",
        "valor_moedas": 270,
        "energia_concedida": 12,
        "chance_obter_percentual": 0.6,
    },
    {
        "nome": "Gema Opaca",
        "tier": "Comum",
        "valor_moedas": 280,
        "energia_concedida": 12,
        "chance_obter_percentual": 0.55,
    },
    {
        "nome": "Lâmina de Treinamento",
        "tier": "Comum",
        "valor_moedas": 290,
        "energia_concedida": 13,
        "chance_obter_percentual": 0.5,
    },
    {
        "nome": "Medalhão Quebrado",
        "tier": "Comum",
        "valor_moedas": 300,
        "energia_concedida": 13,
        "chance_obter_percentual": 0.45,
    },
    {
        "nome": "Óculos Comuns",
        "tier": "Comum",
        "valor_moedas": 310,
        "energia_concedida": 14,
        "chance_obter_percentual": 0.4,
    },
    {
        "nome": "Pingente de Osso",
        "tier": "Comum",
        "valor_moedas": 320,
        "energia_concedida": 14,
        "chance_obter_percentual": 0.35,
    },
    {
        "nome": "Saco de Nozes",
        "tier": "Comum",
        "valor_moedas": 330,
        "energia_concedida": 15,
        "chance_obter_percentual": 0.3,
    },
    {
        "nome": "Talismã Gasto",
        "tier": "Comum",
        "valor_moedas": 340,
        "energia_concedida": 15,
        "chance_obter_percentual": 0.25,
    },
    {
        "nome": "Túnica Rasgada",
        "tier": "Comum",
        "valor_moedas": 350,
        "energia_concedida": 16,
        "chance_obter_percentual": 0.2,
    },
    {
        "nome": "Anel de Cobre",
        "tier": "Comum",
        "valor_moedas": 360,
        "energia_concedida": 16,
        "chance_obter_percentual": 0.18,
    },
    {
        "nome": "Cajado Rachado",
        "tier": "Comum",
        "valor_moedas": 370,
        "energia_concedida": 17,
        "chance_obter_percentual": 0.16,
    },
    {
        "nome": "Diário Vazio",
        "tier": "Comum",
        "valor_moedas": 380,
        "energia_concedida": 17,
        "chance_obter_percentual": 0.14,
    },
    {
        "nome": "Espada Enferrujada",
        "tier": "Comum",
        "valor_moedas": 390,
        "energia_concedida": 18,
        "chance_obter_percentual": 0.12,
    },
    {
        "nome": "Frasco de Areia",
        "tier": "Comum",
        "valor_moedas": 400,
        "energia_concedida": 18,
        "chance_obter_percentual": 0.1,
    },
    {
        "nome": "Gema Sem Brilho",
        "tier": "Comum",
        "valor_moedas": 410,
        "energia_concedida": 19,
        "chance_obter_percentual": 0.09,
    },
    {
        "nome": "Livro Velho",
        "tier": "Comum",
        "valor_moedas": 420,
        "energia_concedida": 19,
        "chance_obter_percentual": 0.08,
    },
    {
        "nome": "Luvas Rasgadas",
        "tier": "Comum",
        "valor_moedas": 430,
        "energia_concedida": 20,
        "chance_obter_percentual": 0.07,
    },
    {
        "nome": "Máscara de Pano",
        "tier": "Comum",
        "valor_moedas": 440,
        "energia_concedida": 20,
        "chance_obter_percentual": 0.06,
    },
    # --- Relíquias Incomuns (Bons Itens, Mas Mais Comuns) ---
    {
        "nome": "Corrente do Exílio",
        "tier": "Incomum",
        "valor_moedas": 1000,
        "energia_concedida": 25,
        "chance_obter_percentual": 0.05,
    },
    {
        "nome": "Chave do Labirinto",
        "tier": "Incomum",
        "valor_moedas": 1200,
        "energia_concedida": 27,
        "chance_obter_percentual": 0.045,
    },
    {
        "nome": "Relíquia do Dragão Ancestral",
        "tier": "Incomum",
        "valor_moedas": 1400,
        "energia_concedida": 29,
        "chance_obter_percentual": 0.04,
    },
    {
        "nome": "Gema do Eclipse Lunar",
        "tier": "Incomum",
        "valor_moedas": 1600,
        "energia_concedida": 31,
        "chance_obter_percentual": 0.035,
    },
    {
        "nome": "Pingente do Abissal",
        "tier": "Incomum",
        "valor_moedas": 1800,
        "energia_concedida": 33,
        "chance_obter_percentual": 0.03,
    },
    {
        "nome": "Cetro da Tempestade",
        "tier": "Incomum",
        "valor_moedas": 2000,
        "energia_concedida": 35,
        "chance_obter_percentual": 0.025,
    },
    {
        "nome": "Chifre do Leviatã",
        "tier": "Incomum",
        "valor_moedas": 2200,
        "energia_concedida": 37,
        "chance_obter_percentual": 0.02,
    },
    {
        "nome": "Escama do Dragão Negro",
        "tier": "Incomum",
        "valor_moedas": 2400,
        "energia_concedida": 39,
        "chance_obter_percentual": 0.015,
    },
    {
        "nome": "Fragmento da Alma",
        "tier": "Incomum",
        "valor_moedas": 2600,
        "energia_concedida": 41,
        "chance_obter_percentual": 0.012,
    },
    {
        "nome": "Cristal das Profundezas",
        "tier": "Incomum",
        "valor_moedas": 2800,
        "energia_concedida": 43,
        "chance_obter_percentual": 0.01,
    },
    {
        "nome": "Colar da Verdade",
        "tier": "Incomum",
        "valor_moedas": 3000,
        "energia_concedida": 45,
        "chance_obter_percentual": 0.009,
    },
    {
        "nome": "Runas do Guardião",
        "tier": "Incomum",
        "valor_moedas": 3200,
        "energia_concedida": 47,
        "chance_obter_percentual": 0.008,
    },
    {
        "nome": "Espelho do Destino",
        "tier": "Incomum",
        "valor_moedas": 3400,
        "energia_concedida": 49,
        "chance_obter_percentual": 0.007,
    },
    {
        "nome": "Máscara do Vampiro",
        "tier": "Incomum",
        "valor_moedas": 3600,
        "energia_concedida": 51,
        "chance_obter_percentual": 0.006,
    },
    {
        "nome": "Medalhão da Luz Pura",
        "tier": "Incomum",
        "valor_moedas": 3800,
        "energia_concedida": 53,
        "chance_obter_percentual": 0.005,
    },
    {
        "nome": "Lâmina do Crepúsculo",
        "tier": "Incomum",
        "valor_moedas": 4000,
        "energia_concedida": 55,
        "chance_obter_percentual": 0.004,
    },
    {
        "nome": "Amuleto das Almas Perdidas",
        "tier": "Incomum",
        "valor_moedas": 4200,
        "energia_concedida": 57,
        "chance_obter_percentual": 0.003,
    },
    {
        "nome": "Pedra do Vórtice",
        "tier": "Incomum",
        "valor_moedas": 4400,
        "energia_concedida": 59,
        "chance_obter_percentual": 0.002,
    },
    {
        "nome": "Essência da Vida Eterna",
        "tier": "Incomum",
        "valor_moedas": 4600,
        "energia_concedida": 61,
        "chance_obter_percentual": 0.001,
    },
    {
        "nome": "Orbe do Caos Abissal",
        "tier": "Incomum",
        "valor_moedas": 4800,
        "energia_concedida": 63,
        "chance_obter_percentual": 0.0009,
    },
    # --- Relíquias Raras (Itens Fortes, Difíceis de Achar) ---
    {
        "nome": "Olho do Rei Vampiro",
        "tier": "Rara",
        "valor_moedas": 10000,
        "energia_concedida": 70,
        "chance_obter_percentual": 0.0008,
    },
    {
        "nome": "Diamante Amaldiçoado",
        "tier": "Rara",
        "valor_moedas": 12000,
        "energia_concedida": 75,
        "chance_obter_percentual": 0.0007,
    },
    {
        "nome": "Pingente do Espaço",
        "tier": "Rara",
        "valor_moedas": 14000,
        "energia_concedida": 80,
        "chance_obter_percentual": 0.0006,
    },
    {
        "nome": "Tecla Shift",
        "tier": "Rara",
        "valor_moedas": 16000,
        "energia_concedida": 85,
        "chance_obter_percentual": 0.0005,
    },
    {
        "nome": "Fragmento do Caos",
        "tier": "Rara",
        "valor_moedas": 18000,
        "energia_concedida": 90,
        "chance_obter_percentual": 0.00045,
    },
    {
        "nome": "Amuleto da Eternidade",
        "tier": "Rara",
        "valor_moedas": 20000,
        "energia_concedida": 95,
        "chance_obter_percentual": 0.0004,
    },
    {
        "nome": "Coração de Fênix",
        "tier": "Rara",
        "valor_moedas": 22000,
        "energia_concedida": 100,
        "chance_obter_percentual": 0.00035,
    },
    {
        "nome": "Lâmina do Destino",
        "tier": "Rara",
        "valor_moedas": 24000,
        "energia_concedida": 105,
        "chance_obter_percentual": 0.0003,
    },
    {
        "nome": "Escudo dos Ancestrais",
        "tier": "Rara",
        "valor_moedas": 26000,
        "energia_concedida": 110,
        "chance_obter_percentual": 0.00025,
    },
    {
        "nome": "Selo do Abismo",
        "tier": "Rara",
        "valor_moedas": 28000,
        "energia_concedida": 115,
        "chance_obter_percentual": 0.0002,
    },
    {
        "nome": "Orbe das Sombras",
        "tier": "Rara",
        "valor_moedas": 30000,
        "energia_concedida": 120,
        "chance_obter_percentual": 0.00018,
    },
    {
        "nome": "Máscara do Esquecimento",
        "tier": "Rara",
        "valor_moedas": 32000,
        "energia_concedida": 125,
        "chance_obter_percentual": 0.00016,
    },
    {
        "nome": "Pedra da Alvorada",
        "tier": "Rara",
        "valor_moedas": 34000,
        "energia_concedida": 130,
        "chance_obter_percentual": 0.00014,
    },
    {
        "nome": "Essência do Vento",
        "tier": "Rara",
        "valor_moedas": 36000,
        "energia_concedida": 135,
        "chance_obter_percentual": 0.00012,
    },
    {
        "nome": "Cajado do Arcanjo",
        "tier": "Rara",
        "valor_moedas": 38000,
        "energia_concedida": 140,
        "chance_obter_percentual": 0.0001,
    },
    {
        "nome": "Talismã das Estrelas",
        "tier": "Rara",
        "valor_moedas": 40000,
        "energia_concedida": 145,
        "chance_obter_percentual": 0.00009,
    },
    {
        "nome": "Medalhão do Guardião",
        "tier": "Rara",
        "valor_moedas": 42000,
        "energia_concedida": 150,
        "chance_obter_percentual": 0.00008,
    },
    {
        "nome": "Cristal do Tempo",
        "tier": "Rara",
        "valor_moedas": 44000,
        "energia_concedida": 155,
        "chance_obter_percentual": 0.00007,
    },
    {
        "nome": "Fragmento de Neve Eterna",
        "tier": "Rara",
        "valor_moedas": 46000,
        "energia_concedida": 160,
        "chance_obter_percentual": 0.00006,
    },
    {
        "nome": "Olho da Serpente",
        "tier": "Rara",
        "valor_moedas": 48000,
        "energia_concedida": 165,
        "chance_obter_percentual": 0.00005,
    },
    # --- Relíquias Épicas (Artefatos Poderosos e Raros) ---
    {
        "nome": "Prisma do Servo",
        "tier": "Épica",
        "valor_moedas": 100000,
        "energia_concedida": 200,
        "chance_obter_percentual": 0.00001,
    },
    {
        "nome": "Prisma do Drácula",
        "tier": "Épica",
        "valor_moedas": 120000,
        "energia_concedida": 220,
        "chance_obter_percentual": 0.000009,
    },
    {
        "nome": "Coroa do Imperador Sombrio",
        "tier": "Épica",
        "valor_moedas": 140000,
        "energia_concedida": 240,
        "chance_obter_percentual": 0.000008,
    },
    {
        "nome": "Orbe do Caos Abissal",
        "tier": "Épica",
        "valor_moedas": 160000,
        "energia_concedida": 260,
        "chance_obter_percentual": 0.000007,
    },
    {
        "nome": "Gema do Dragão Celestial",
        "tier": "Épica",
        "valor_moedas": 180000,
        "energia_concedida": 280,
        "chance_obter_percentual": 0.000006,
    },
    {
        "nome": "Chama Eterna",
        "tier": "Épica",
        "valor_moedas": 200000,
        "energia_concedida": 300,
        "chance_obter_percentual": 0.000005,
    },
    {
        "nome": "Máscara da Fênix",
        "tier": "Épica",
        "valor_moedas": 220000,
        "energia_concedida": 320,
        "chance_obter_percentual": 0.000004,
    },
    {
        "nome": "Escudo do Guardião Ancestral",
        "tier": "Épica",
        "valor_moedas": 240000,
        "energia_concedida": 340,
        "chance_obter_percentual": 0.000003,
    },
    {
        "nome": "Prismas Gêmeos",
        "tier": "Épica",
        "valor_moedas": 260000,
        "energia_concedida": 360,
        "chance_obter_percentual": 0.000002,
    },
    {
        "nome": "Lâmina do Crepúsculo Profundo",
        "tier": "Épica",
        "valor_moedas": 280000,
        "energia_concedida": 380,
        "chance_obter_percentual": 0.000001,
    },
    # --- Relíquias Míticas (Únicas, Artefatos Supremos) ---
    {
        "nome": "Alma do Infinito",
        "tier": "Mítica",
        "valor_moedas": 1000000,
        "energia_concedida": 1000,  # Pode ser interpretada como ilimitada em jogo
        "chance_obter_percentual": 0.0000001,
    },
    {
        "nome": "Catalisador",
        "tier": "Mítica",
        "valor_moedas": 1500000,
        "energia_concedida": 1200,
        "chance_obter_percentual": 0.00000009,
    },
    {
        "nome": "Monolito do Eclipse",
        "tier": "Mítica",
        "valor_moedas": 2000000,
        "energia_concedida": 1500,
        "chance_obter_percentual": 0.00000008,
    },
    {
        "nome": "Monolito do Sol",
        "tier": "Mítica",
        "valor_moedas": 2500000,
        "energia_concedida": 1800,
        "chance_obter_percentual": 0.00000007,
    },
    {
        "nome": "Monolito das Trevas",
        "tier": "Mítica",
        "valor_moedas": 3000000,
        "energia_concedida": 2000,
        "chance_obter_percentual": 0.00000006,
    },
    {
        "nome": "Monolito do Dragão",
        "tier": "Mítica",
        "valor_moedas": 3500000,
        "energia_concedida": 2200,
        "chance_obter_percentual": 0.00000005,
    },
    {
        "nome": "The Zero",
        "tier": "Mítica",
        "valor_moedas": 4000000,
        "energia_concedida": 2500,
        "chance_obter_percentual": 0.00000004,
    },
    {
        "nome": "Cristalina Total",
        "tier": "Mítica",
        "valor_moedas": 4500000,
        "energia_concedida": 2800,
        "chance_obter_percentual": 0.00000003,
    },
    {
        "nome": "Colar do Rei Henrique",
        "tier": "Mítica",
        "valor_moedas": 5000000,
        "energia_concedida": 3000,
        "chance_obter_percentual": 0.00000002,
    },
    {
        "nome": "Prisma do Caos",
        "tier": "Mítica",
        "valor_moedas": 5500000,
        "energia_concedida": 3200,
        "chance_obter_percentual": 0.00000001,
    },
]
